<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/asynq.proto

namespace Wuwuseo\HibikenAsynqClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SchedulerEnqueueEvent holds information about an enqueue event
 * by a scheduler.
 *
 * Generated from protobuf message <code>asynq.SchedulerEnqueueEvent</code>
 */
class SchedulerEnqueueEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the task that was enqueued.
     *
     * Generated from protobuf field <code>string task_id = 1;</code>
     */
    protected $task_id = '';
    /**
     * Time the task was enqueued.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp enqueue_time = 2;</code>
     */
    protected $enqueue_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task_id
     *           ID of the task that was enqueued.
     *     @type \Google\Protobuf\Timestamp $enqueue_time
     *           Time the task was enqueued.
     * }
     */
    public function __construct($data = NULL) {
        \Wuwuseo\HibikenAsynqClient\metadata\Asynq::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the task that was enqueued.
     *
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * ID of the task that was enqueued.
     *
     * Generated from protobuf field <code>string task_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Time the task was enqueued.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp enqueue_time = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEnqueueTime()
    {
        return $this->enqueue_time;
    }

    public function hasEnqueueTime()
    {
        return isset($this->enqueue_time);
    }

    public function clearEnqueueTime()
    {
        unset($this->enqueue_time);
    }

    /**
     * Time the task was enqueued.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp enqueue_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEnqueueTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->enqueue_time = $var;

        return $this;
    }

}

