<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/asynq.proto

namespace Wuwuseo\HibikenAsynqClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ServerInfo holds information about a running server.
 *
 * Generated from protobuf message <code>asynq.ServerInfo</code>
 */
class ServerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Host machine the server is running on.
     *
     * Generated from protobuf field <code>string host = 1;</code>
     */
    protected $host = '';
    /**
     * PID of the server process.
     *
     * Generated from protobuf field <code>int32 pid = 2;</code>
     */
    protected $pid = 0;
    /**
     * Unique identifier for this server.
     *
     * Generated from protobuf field <code>string server_id = 3;</code>
     */
    protected $server_id = '';
    /**
     * Maximum number of concurrency this server will use.
     *
     * Generated from protobuf field <code>int32 concurrency = 4;</code>
     */
    protected $concurrency = 0;
    /**
     * List of queue names with their priorities.
     * The server will consume tasks from the queues and prioritize
     * queues with higher priority numbers.
     *
     * Generated from protobuf field <code>map<string, int32> queues = 5;</code>
     */
    private $queues;
    /**
     * If set, the server will always consume tasks from a queue with higher
     * priority.
     *
     * Generated from protobuf field <code>bool strict_priority = 6;</code>
     */
    protected $strict_priority = false;
    /**
     * Status indicates the status of the server.
     *
     * Generated from protobuf field <code>string status = 7;</code>
     */
    protected $status = '';
    /**
     * Time this server was started.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 8;</code>
     */
    protected $start_time = null;
    /**
     * Number of workers currently processing tasks.
     *
     * Generated from protobuf field <code>int32 active_worker_count = 9;</code>
     */
    protected $active_worker_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *           Host machine the server is running on.
     *     @type int $pid
     *           PID of the server process.
     *     @type string $server_id
     *           Unique identifier for this server.
     *     @type int $concurrency
     *           Maximum number of concurrency this server will use.
     *     @type array|\Google\Protobuf\Internal\MapField $queues
     *           List of queue names with their priorities.
     *           The server will consume tasks from the queues and prioritize
     *           queues with higher priority numbers.
     *     @type bool $strict_priority
     *           If set, the server will always consume tasks from a queue with higher
     *           priority.
     *     @type string $status
     *           Status indicates the status of the server.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Time this server was started.
     *     @type int $active_worker_count
     *           Number of workers currently processing tasks.
     * }
     */
    public function __construct($data = NULL) {
        \Wuwuseo\HibikenAsynqClient\metadata\Asynq::initOnce();
        parent::__construct($data);
    }

    /**
     * Host machine the server is running on.
     *
     * Generated from protobuf field <code>string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Host machine the server is running on.
     *
     * Generated from protobuf field <code>string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * PID of the server process.
     *
     * Generated from protobuf field <code>int32 pid = 2;</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * PID of the server process.
     *
     * Generated from protobuf field <code>int32 pid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkInt32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Unique identifier for this server.
     *
     * Generated from protobuf field <code>string server_id = 3;</code>
     * @return string
     */
    public function getServerId()
    {
        return $this->server_id;
    }

    /**
     * Unique identifier for this server.
     *
     * Generated from protobuf field <code>string server_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setServerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_id = $var;

        return $this;
    }

    /**
     * Maximum number of concurrency this server will use.
     *
     * Generated from protobuf field <code>int32 concurrency = 4;</code>
     * @return int
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    /**
     * Maximum number of concurrency this server will use.
     *
     * Generated from protobuf field <code>int32 concurrency = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setConcurrency($var)
    {
        GPBUtil::checkInt32($var);
        $this->concurrency = $var;

        return $this;
    }

    /**
     * List of queue names with their priorities.
     * The server will consume tasks from the queues and prioritize
     * queues with higher priority numbers.
     *
     * Generated from protobuf field <code>map<string, int32> queues = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getQueues()
    {
        return $this->queues;
    }

    /**
     * List of queue names with their priorities.
     * The server will consume tasks from the queues and prioritize
     * queues with higher priority numbers.
     *
     * Generated from protobuf field <code>map<string, int32> queues = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setQueues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->queues = $arr;

        return $this;
    }

    /**
     * If set, the server will always consume tasks from a queue with higher
     * priority.
     *
     * Generated from protobuf field <code>bool strict_priority = 6;</code>
     * @return bool
     */
    public function getStrictPriority()
    {
        return $this->strict_priority;
    }

    /**
     * If set, the server will always consume tasks from a queue with higher
     * priority.
     *
     * Generated from protobuf field <code>bool strict_priority = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setStrictPriority($var)
    {
        GPBUtil::checkBool($var);
        $this->strict_priority = $var;

        return $this;
    }

    /**
     * Status indicates the status of the server.
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Status indicates the status of the server.
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Time this server was started.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Time this server was started.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Number of workers currently processing tasks.
     *
     * Generated from protobuf field <code>int32 active_worker_count = 9;</code>
     * @return int
     */
    public function getActiveWorkerCount()
    {
        return $this->active_worker_count;
    }

    /**
     * Number of workers currently processing tasks.
     *
     * Generated from protobuf field <code>int32 active_worker_count = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setActiveWorkerCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->active_worker_count = $var;

        return $this;
    }

}

